### ISSUE TITLE
FTP connexion

### ISSUE THREAD

**Issue by Lepterois** [chrishamm/RepRapFirmware#4]
Hi!
I've done the firmware update to the 1.18.1 on my Ormerod2. Since this update I canot connect anymore to my Ormerod in FTP using Filezilla.
What can I do for this? before I used Version 1.09 and it was working fine. What is changing between the 2 versions?

Thanks in advance

**Comment by chrishamm** [comment]
I think after upgrading you need to enable the FTP protocol explicitly by adding "M586 P1 S1" to your config.g.

**Comment by Lepterois** [comment]
ok thanks! it works perfectly now!
